export enum constants {
  DEFAULT_CARD_HEIGHT = 300,
  DEFAULT_CARD_WIDTH = 300,
  DEFAULT_CARD_BORDER_COLOR = "#f58800",
  DEFAULT_CARD_BACKGROUND_COLOR = "#FFFFFF",
  DEFAULT_CARD_COLOR = "#1a4645",
}
