export const DEFAULT_CARD_HEIGHT = 300;
export const DEFAULT_CARD_WIDTH = 300;
export const DEFAULT_CARD_BORDER_COLOR = "#f58800";
export const DEFAULT_CARD_BACKGROUND_COLOR = "#FFFFFF";
export const DEFAULT_CARD_COLOR = "#1a4645";
